# FFI bindings to Nickel's official C API (v2.0.0)
# Low-level wrappers in libnickel.jl (generated by Clang.jl)
# This file provides the convenience layer: library discovery, eval, tree-walk.

using LazyArtifacts
using Libdl

# Platform-specific library name
const LIB_NAME = if Sys.isapple()
    "libnickel_lang.dylib"
elseif Sys.iswindows()
    "nickel_lang.dll"
else
    "libnickel_lang.so"
end

# Find library: local deps/ -> artifact -> not found
function _find_library_path()
    # Local deps/ (custom builds, HPC overrides)
    local_path = joinpath(@__DIR__, "..", "deps", LIB_NAME)
    if isfile(local_path)
        return local_path
    end

    # Artifact (auto-selects platform, triggers lazy download)
    try
        artifact_dir = @artifact_str("libnickel_lang")
        lib_path = joinpath(artifact_dir, LIB_NAME)
        if isfile(lib_path)
            return lib_path
        end
    catch
    end

    return nothing
end

# Library path and availability resolved at runtime via __init__(),
# not at precompile time. This allows Pkg.build() to install the library
# after initial precompilation (JLL pattern, requires Julia 1.6+).
libnickel_lang::String = ""
FFI_AVAILABLE::Bool = false

function __init_ffi__()
    path = _find_library_path()
    if path !== nothing
        try
            Libdl.dlopen(path)
            global libnickel_lang = path
            global FFI_AVAILABLE = true
        catch e
            @warn "Found libnickel_lang at $path but failed to load it: $e\n" *
                  "Build from source with: build_ffi()"
        end
    end
end

include("libnickel.jl")
import .LibNickel
const L = LibNickel

"""
    check_ffi_available() -> Bool

Check if the Nickel C API library is available.
"""
check_ffi_available() = FFI_AVAILABLE

"""
    build_ffi()

Build the Nickel C API library from source. Requires Rust (cargo).
Restarts the FFI after building so you don't need to restart Julia.
"""
function build_ffi()
    build_script = joinpath(@__DIR__, "..", "deps", "build.jl")
    @info "Building Nickel C API library from source..."
    withenv("NICKELEVAL_BUILD_FFI" => "true") do
        include(build_script)
    end
    # Re-initialize to pick up the newly built library
    __init_ffi__()
    if FFI_AVAILABLE
        @info "FFI ready. nickel_eval() is now available."
    else
        error("Build completed but library still not loadable. Check the build output above.")
    end
end

function _check_ffi_available()
    FFI_AVAILABLE && return
    error("Nickel C API library not available.\n\n" *
          "Build from Julia:  using NickelEval; build_ffi()\n" *
          "Build from shell:  NICKELEVAL_BUILD_FFI=true julia -e 'using Pkg; Pkg.build(\"NickelEval\")'\n")
end

# ── Tree-walk: convert C API expr to Julia value ─────────────────────────────

function _walk_expr(expr::Ptr{L.nickel_expr})
    if L.nickel_expr_is_null(expr) != 0
        return nothing
    elseif L.nickel_expr_is_bool(expr) != 0
        return L.nickel_expr_as_bool(expr) != 0
    elseif L.nickel_expr_is_number(expr) != 0
        num = L.nickel_expr_as_number(expr)  # borrowed, no free
        if L.nickel_number_is_i64(num) != 0
            return L.nickel_number_as_i64(num)
        else
            return Float64(L.nickel_number_as_f64(num))
        end
    elseif L.nickel_expr_is_str(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_str(expr, out_ptr)
        return unsafe_string(out_ptr[], len)
    elseif L.nickel_expr_is_array(expr) != 0
        arr = L.nickel_expr_as_array(expr)  # borrowed, no free
        n = Int(L.nickel_array_len(arr))
        result = Vector{Any}(undef, n)
        if n > 0
            elem = L.nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    L.nickel_array_get(arr, UInt(i), elem)
                    result[i+1] = _walk_expr(elem)
                end
            finally
                L.nickel_expr_free(elem)
            end
        end
        return result
    elseif L.nickel_expr_is_record(expr) != 0
        rec = L.nickel_expr_as_record(expr)  # borrowed, no free
        n = Int(L.nickel_record_len(rec))
        result = Dict{String, Any}()
        if n > 0
            key_ptr = Ref{Ptr{Cchar}}(C_NULL)
            key_len = Ref{Csize_t}(0)
            val_expr = L.nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    L.nickel_record_key_value_by_index(rec, UInt(i), key_ptr, key_len, val_expr)
                    key = unsafe_string(key_ptr[], key_len[])
                    result[key] = _walk_expr(val_expr)
                end
            finally
                L.nickel_expr_free(val_expr)
            end
        end
        return result
    elseif L.nickel_expr_is_enum_variant(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        arg_expr = L.nickel_expr_alloc()
        try
            len = L.nickel_expr_as_enum_variant(expr, out_ptr, arg_expr)
            tag = Symbol(unsafe_string(out_ptr[], len))
            arg = _walk_expr(arg_expr)
            return NickelEnum(tag, arg)
        finally
            L.nickel_expr_free(arg_expr)
        end
    elseif L.nickel_expr_is_enum_tag(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_enum_tag(expr, out_ptr)
        tag = Symbol(unsafe_string(out_ptr[], len))
        return NickelEnum(tag, nothing)
    else
        error("Unknown Nickel expression type")
    end
end

# ── Error extraction ──────────────────────────────────────────────────────────

function _throw_nickel_error(err::Ptr{L.nickel_error})
    out_str = L.nickel_string_alloc()
    try
        L.nickel_error_format_as_string(err, out_str, L.NICKEL_ERROR_FORMAT_TEXT)
        data_ptr = Ref{Ptr{Cchar}}(C_NULL)
        data_len = Ref{Csize_t}(0)
        L.nickel_string_data(out_str, data_ptr, data_len)
        msg = unsafe_string(data_ptr[], data_len[])
        throw(NickelError(msg))
    finally
        L.nickel_string_free(out_str)
    end
end

# ── Public API ────────────────────────────────────────────────────────────────

"""
    nickel_eval(code::String) -> Any

Evaluate Nickel code and return a Julia value.

Returns native Julia types: Int64, Float64, Bool, String, nothing,
Vector{Any}, Dict{String,Any}, or NickelEnum.

# Examples
```julia
julia> nickel_eval("1 + 2")
3

julia> nickel_eval("{ a = 1, b = 2 }")
Dict{String, Any}("a" => 1, "b" => 2)

julia> nickel_eval("let x = 5 in x * 2")
10
```
"""
function nickel_eval(code::String)
    _check_ffi_available()
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    try
        result = L.nickel_context_eval_deep(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _walk_expr(expr)
    finally
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

"""
    nickel_eval(code::String, ::Type{T}) -> T

Evaluate Nickel code and convert to type T.
Supports Dict, Vector, and NamedTuple conversions.

# Examples
```julia
julia> nickel_eval("42", Int)
42

julia> nickel_eval("{ a = 1, b = 2 }", Dict{String, Int})
Dict{String, Int64}("a" => 1, "b" => 2)

julia> nickel_eval("[1, 2, 3]", Vector{Int})
[1, 2, 3]

julia> nickel_eval("{ x = 1.5, y = 2.5 }", @NamedTuple{x::Float64, y::Float64})
(x = 1.5, y = 2.5)
```
"""
function nickel_eval(code::String, ::Type{T}) where T
    result = nickel_eval(code)
    return _convert_result(T, result)
end

# ── Type conversion helpers ───────────────────────────────────────────────────

_convert_result(::Type{T}, x) where T = convert(T, x)

function _convert_result(::Type{T}, d::Dict{String,Any}) where T <: NamedTuple
    fields = fieldnames(T)
    types = fieldtypes(T)
    values = Tuple(_convert_result(types[i], d[String(fields[i])]) for i in eachindex(fields))
    return T(values)
end

function _convert_result(::Type{Dict{K,V}}, d::Dict{String,Any}) where {K,V}
    return Dict{K,V}(K(k) => _convert_result(V, v) for (k, v) in d)
end

function _convert_result(::Type{Vector{T}}, v::Vector{Any}) where T
    return T[_convert_result(T, x) for x in v]
end

# ── File evaluation ───────────────────────────────────────────────────────────

"""
    nickel_eval_file(path::String) -> Any

Evaluate a Nickel file. Supports `import` statements resolved relative
to the file's directory.

Returns native Julia types: Int64, Float64, Bool, String, nothing,
Vector{Any}, Dict{String,Any}, or NickelEnum.

# Examples
```julia
julia> nickel_eval_file("config.ncl")
Dict{String, Any}("host" => "localhost", "port" => 8080)
```
"""
function nickel_eval_file(path::String)
    _check_ffi_available()
    abs_path = abspath(path)
    if !isfile(abs_path)
        throw(NickelError("File not found: $abs_path"))
    end
    code = read(abs_path, String)
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    try
        # Set source name to the absolute file path so Nickel can resolve imports
        # relative to the file's directory.
        GC.@preserve abs_path begin
            L.nickel_context_set_source_name(ctx, Base.unsafe_convert(Ptr{Cchar}, abs_path))
        end
        result = L.nickel_context_eval_deep(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _walk_expr(expr)
    finally
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

# ── Export (serialization) ────────────────────────────────────────────────────

function _eval_and_serialize(code::String, serialize_fn)
    _check_ffi_available()
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    out_str = L.nickel_string_alloc()
    try
        result = L.nickel_context_eval_deep_for_export(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        ser_result = serialize_fn(ctx, expr, out_str, err)
        if ser_result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        data_ptr = Ref{Ptr{Cchar}}(C_NULL)
        data_len = Ref{Csize_t}(0)
        L.nickel_string_data(out_str, data_ptr, data_len)
        return unsafe_string(data_ptr[], data_len[])
    finally
        L.nickel_string_free(out_str)
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

"""
    nickel_to_json(code::String) -> String

Evaluate Nickel code and export to a JSON string.

# Examples
```julia
julia> nickel_to_json("{ a = 1, b = \"hello\" }")
"{\\"a\\": 1,\\"b\\": \\"hello\\"}"
```
"""
nickel_to_json(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_json)

"""
    nickel_to_yaml(code::String) -> String

Evaluate Nickel code and export to a YAML string.

# Examples
```julia
julia> nickel_to_yaml("{ a = 1 }")
"a: 1\\n"
```
"""
nickel_to_yaml(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_yaml)

"""
    nickel_to_toml(code::String) -> String

Evaluate Nickel code and export to a TOML string.

# Examples
```julia
julia> nickel_to_toml("{ a = 1 }")
"a = 1\\n"
```
"""
nickel_to_toml(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_toml)

# ── Lazy evaluation ──────────────────────────────────────────────────────────

function _check_session_open(session::NickelSession)
    session.closed && throw(ArgumentError("NickelSession is closed"))
end

# Allocate a new expr tracked by the session
function _tracked_expr_alloc(session::NickelSession)
    expr = L.nickel_expr_alloc()
    push!(session.exprs, Ptr{Cvoid}(expr))
    return expr
end

function Base.close(session::NickelSession)
    session.closed && return
    session.closed = true
    for expr_ptr in session.exprs
        L.nickel_expr_free(Ptr{L.nickel_expr}(expr_ptr))
    end
    empty!(session.exprs)
    L.nickel_context_free(Ptr{L.nickel_context}(session.ctx))
    return nothing
end

Base.close(v::NickelValue) = close(getfield(v, :session))

"""
    nickel_open(f, code::String)
    nickel_open(code::String) -> NickelValue

Evaluate Nickel code shallowly and return a lazy `NickelValue`.
Sub-expressions are evaluated on demand when accessed via `.field` or `["field"]`.

# Do-block (preferred)
```julia
nickel_open("{ x = 1, y = 2 }") do cfg
    cfg.x  # => 1 (only evaluates x)
end
```

# Manual
```julia
cfg = nickel_open("{ x = 1, y = 2 }")
cfg.x  # => 1
close(cfg)
```
"""
function nickel_open(f::Function, path_or_code::String)
    val = nickel_open(path_or_code)
    try
        return f(val)
    finally
        close(val)
    end
end

function nickel_open(path_or_code::String)
    _check_ffi_available()
    # Detect file path: ends with .ncl AND exists on disk
    if endswith(path_or_code, ".ncl") && isfile(abspath(path_or_code))
        return _nickel_open_file(path_or_code)
    end
    return _nickel_open_code(path_or_code)
end

function _nickel_open_file(path::String)
    abs_path = abspath(path)
    if !isfile(abs_path)
        throw(NickelError("File not found: $abs_path"))
    end
    code = read(abs_path, String)
    ctx = L.nickel_context_alloc()
    session = NickelSession(Ptr{Cvoid}(ctx), Ptr{Cvoid}[], false)
    finalizer(close, session)
    expr = _tracked_expr_alloc(session)
    err = L.nickel_error_alloc()
    try
        GC.@preserve abs_path begin
            L.nickel_context_set_source_name(ctx, Base.unsafe_convert(Ptr{Cchar}, abs_path))
        end
        result = L.nickel_context_eval_shallow(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return NickelValue(session, Ptr{Cvoid}(expr))
    catch
        close(session)
        rethrow()
    finally
        L.nickel_error_free(err)
    end
end

function _nickel_open_code(code::String)
    ctx = L.nickel_context_alloc()
    session = NickelSession(Ptr{Cvoid}(ctx), Ptr{Cvoid}[], false)
    finalizer(close, session)
    expr = _tracked_expr_alloc(session)
    err = L.nickel_error_alloc()
    try
        result = L.nickel_context_eval_shallow(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return NickelValue(session, Ptr{Cvoid}(expr))
    catch
        close(session)
        rethrow()
    finally
        L.nickel_error_free(err)
    end
end

# Given a shallow-eval'd expr, return a Julia value (primitive) or NickelValue (compound).
# Primitives (null, bool, number, string, bare enum tag) are converted immediately.
# Compound types (record, array, enum variant) stay lazy as a new NickelValue.
function _resolve_value(session::NickelSession, expr::Ptr{L.nickel_expr})
    if L.nickel_expr_is_null(expr) != 0
        return nothing
    elseif L.nickel_expr_is_bool(expr) != 0
        return L.nickel_expr_as_bool(expr) != 0
    elseif L.nickel_expr_is_number(expr) != 0
        num = L.nickel_expr_as_number(expr)
        if L.nickel_number_is_i64(num) != 0
            return L.nickel_number_as_i64(num)
        else
            return Float64(L.nickel_number_as_f64(num))
        end
    elseif L.nickel_expr_is_str(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_str(expr, out_ptr)
        return unsafe_string(out_ptr[], len)
    elseif L.nickel_expr_is_enum_tag(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_enum_tag(expr, out_ptr)
        tag = Symbol(unsafe_string(out_ptr[], len))
        return NickelEnum(tag, nothing)
    else
        # record, array, or enum variant — stay lazy
        return NickelValue(session, Ptr{Cvoid}(expr))
    end
end

# Evaluate a sub-expression shallowly, then resolve to Julia value or NickelValue.
function _eval_and_resolve(session::NickelSession, sub_expr::Ptr{L.nickel_expr})
    ctx = Ptr{L.nickel_context}(session.ctx)
    out_expr = _tracked_expr_alloc(session)
    err = L.nickel_error_alloc()
    try
        result = L.nickel_context_eval_expr_shallow(ctx, sub_expr, out_expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _resolve_value(session, out_expr)
    finally
        L.nickel_error_free(err)
    end
end

"""
    nickel_kind(v::NickelValue) -> Symbol

Return the kind of a lazy Nickel value without evaluating its children.

Returns one of: `:record`, `:array`, `:number`, `:string`, `:bool`, `:null`, `:enum`.
"""
function nickel_kind(v::NickelValue)
    _check_session_open(getfield(v, :session))
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if L.nickel_expr_is_null(expr) != 0
        return :null
    elseif L.nickel_expr_is_bool(expr) != 0
        return :bool
    elseif L.nickel_expr_is_number(expr) != 0
        return :number
    elseif L.nickel_expr_is_str(expr) != 0
        return :string
    elseif L.nickel_expr_is_array(expr) != 0
        return :array
    elseif L.nickel_expr_is_record(expr) != 0
        return :record
    elseif L.nickel_expr_is_enum_variant(expr) != 0 || L.nickel_expr_is_enum_tag(expr) != 0
        return :enum
    else
        error("Unknown Nickel expression type")
    end
end

function Base.show(io::IO, v::NickelValue)
    session = getfield(v, :session)
    if session.closed
        print(io, "NickelValue(<closed>)")
        return
    end
    k = nickel_kind(v)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if k == :record
        rec = L.nickel_expr_as_record(expr)
        n = Int(L.nickel_record_len(rec))
        print(io, "NickelValue(:record, $n field", n == 1 ? "" : "s", ")")
    elseif k == :array
        arr = L.nickel_expr_as_array(expr)
        n = Int(L.nickel_array_len(arr))
        print(io, "NickelValue(:array, $n element", n == 1 ? "" : "s", ")")
    else
        print(io, "NickelValue(:$k)")
    end
end

# ── Materialization ───────────────────────────────────────────────────────────

"""
    collect(v::NickelValue) -> Any

Recursively evaluate and materialize the entire subtree rooted at `v`.
Returns the same types as `nickel_eval`: Dict, Vector, Int64, Float64, etc.
"""
function Base.collect(v::NickelValue)
    session = getfield(v, :session)
    _check_session_open(session)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    return _collect_expr(session, expr)
end

# Recursive collect: shallow-eval each sub-expression, then convert.
# Unlike _walk_expr, this must eval each child before inspecting its type.
function _collect_expr(session::NickelSession, expr::Ptr{L.nickel_expr})
    ctx = Ptr{L.nickel_context}(session.ctx)

    if L.nickel_expr_is_null(expr) != 0
        return nothing
    elseif L.nickel_expr_is_bool(expr) != 0
        return L.nickel_expr_as_bool(expr) != 0
    elseif L.nickel_expr_is_number(expr) != 0
        num = L.nickel_expr_as_number(expr)
        if L.nickel_number_is_i64(num) != 0
            return L.nickel_number_as_i64(num)
        else
            return Float64(L.nickel_number_as_f64(num))
        end
    elseif L.nickel_expr_is_str(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_str(expr, out_ptr)
        return unsafe_string(out_ptr[], len)
    elseif L.nickel_expr_is_array(expr) != 0
        arr = L.nickel_expr_as_array(expr)
        n = Int(L.nickel_array_len(arr))
        result = Vector{Any}(undef, n)
        for i in 0:(n-1)
            elem = _tracked_expr_alloc(session)
            L.nickel_array_get(arr, Csize_t(i), elem)
            evaled = _tracked_expr_alloc(session)
            err = L.nickel_error_alloc()
            try
                r = L.nickel_context_eval_expr_shallow(ctx, elem, evaled, err)
                if r == L.NICKEL_RESULT_ERR
                    _throw_nickel_error(err)
                end
            finally
                L.nickel_error_free(err)
            end
            result[i+1] = _collect_expr(session, evaled)
        end
        return result
    elseif L.nickel_expr_is_record(expr) != 0
        rec = L.nickel_expr_as_record(expr)
        n = Int(L.nickel_record_len(rec))
        result = Dict{String, Any}()
        key_ptr = Ref{Ptr{Cchar}}(C_NULL)
        key_len = Ref{Csize_t}(0)
        for i in 0:(n-1)
            val_expr = _tracked_expr_alloc(session)
            L.nickel_record_key_value_by_index(rec, Csize_t(i), key_ptr, key_len, val_expr)
            key = unsafe_string(key_ptr[], key_len[])
            evaled = _tracked_expr_alloc(session)
            err = L.nickel_error_alloc()
            try
                r = L.nickel_context_eval_expr_shallow(ctx, val_expr, evaled, err)
                if r == L.NICKEL_RESULT_ERR
                    _throw_nickel_error(err)
                end
            finally
                L.nickel_error_free(err)
            end
            result[key] = _collect_expr(session, evaled)
        end
        return result
    elseif L.nickel_expr_is_enum_variant(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        arg_expr = _tracked_expr_alloc(session)
        len = L.nickel_expr_as_enum_variant(expr, out_ptr, arg_expr)
        tag = Symbol(unsafe_string(out_ptr[], len))
        evaled = _tracked_expr_alloc(session)
        err = L.nickel_error_alloc()
        try
            r = L.nickel_context_eval_expr_shallow(ctx, arg_expr, evaled, err)
            if r == L.NICKEL_RESULT_ERR
                _throw_nickel_error(err)
            end
        finally
            L.nickel_error_free(err)
        end
        return NickelEnum(tag, _collect_expr(session, evaled))
    elseif L.nickel_expr_is_enum_tag(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_enum_tag(expr, out_ptr)
        return NickelEnum(Symbol(unsafe_string(out_ptr[], len)), nothing)
    else
        error("Unknown Nickel expression type")
    end
end

# ── Inspection ────────────────────────────────────────────────────────────────

function Base.keys(v::NickelValue)
    session = getfield(v, :session)
    _check_session_open(session)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if L.nickel_expr_is_record(expr) == 0
        throw(ArgumentError("Cannot get keys: NickelValue is not a record"))
    end
    rec = L.nickel_expr_as_record(expr)
    n = Int(L.nickel_record_len(rec))
    result = Vector{String}(undef, n)
    key_ptr = Ref{Ptr{Cchar}}(C_NULL)
    key_len = Ref{Csize_t}(0)
    for i in 0:(n-1)
        L.nickel_record_key_value_by_index(rec, Csize_t(i), key_ptr, key_len,
                                           Ptr{L.nickel_expr}(C_NULL))
        result[i+1] = unsafe_string(key_ptr[], key_len[])
    end
    return result
end

function Base.length(v::NickelValue)
    session = getfield(v, :session)
    _check_session_open(session)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if L.nickel_expr_is_record(expr) != 0
        return Int(L.nickel_record_len(L.nickel_expr_as_record(expr)))
    elseif L.nickel_expr_is_array(expr) != 0
        return Int(L.nickel_array_len(L.nickel_expr_as_array(expr)))
    else
        throw(ArgumentError("Cannot get length: NickelValue is not a record or array"))
    end
end

# ── Navigation ───────────────────────────────────────────────────────────────

function Base.getproperty(v::NickelValue, name::Symbol)
    return _lazy_field_access(v, String(name))
end

function Base.getindex(v::NickelValue, key::String)
    return _lazy_field_access(v, key)
end

function Base.getindex(v::NickelValue, idx::Integer)
    session = getfield(v, :session)
    _check_session_open(session)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if L.nickel_expr_is_array(expr) == 0
        throw(ArgumentError("Cannot index with integer: NickelValue is not an array"))
    end
    arr = L.nickel_expr_as_array(expr)
    n = Int(L.nickel_array_len(arr))
    if idx < 1 || idx > n
        throw(BoundsError(v, idx))
    end
    out_expr = _tracked_expr_alloc(session)
    L.nickel_array_get(arr, Csize_t(idx - 1), out_expr)  # 0-based C API
    return _eval_and_resolve(session, out_expr)
end

function _lazy_field_access(v::NickelValue, key::String)
    session = getfield(v, :session)
    _check_session_open(session)
    expr = Ptr{L.nickel_expr}(getfield(v, :expr))
    if L.nickel_expr_is_record(expr) == 0
        throw(ArgumentError("Cannot access field '$key': NickelValue is not a record"))
    end
    rec = L.nickel_expr_as_record(expr)
    out_expr = _tracked_expr_alloc(session)
    has_value = L.nickel_record_value_by_name(rec, key, out_expr)
    if has_value == 0
        # Check whether the key exists at all
        n = Int(L.nickel_record_len(rec))
        found = false
        key_ptr = Ref{Ptr{Cchar}}(C_NULL)
        key_len = Ref{Csize_t}(0)
        for i in 0:(n-1)
            L.nickel_record_key_value_by_index(rec, Csize_t(i), key_ptr, key_len,
                                               Ptr{L.nickel_expr}(C_NULL))
            if unsafe_string(key_ptr[], key_len[]) == key
                found = true
                break
            end
        end
        if !found
            throw(NickelError("Field '$key' not found in record"))
        end
        throw(NickelError("Field '$key' has no value (contract-only or unevaluated)"))
    end
    return _eval_and_resolve(session, out_expr)
end
