# FFI bindings to Nickel's official C API (v2.0.0)
# Low-level wrappers in libnickel.jl (generated by Clang.jl)
# This file provides the convenience layer: library discovery, eval, tree-walk.

using LazyArtifacts
using Libdl

# Platform-specific library name
const LIB_NAME = if Sys.isapple()
    "libnickel_lang.dylib"
elseif Sys.iswindows()
    "nickel_lang.dll"
else
    "libnickel_lang.so"
end

# Find library: local deps/ -> artifact -> not found
function _find_library_path()
    # Local deps/ (custom builds, HPC overrides)
    local_path = joinpath(@__DIR__, "..", "deps", LIB_NAME)
    if isfile(local_path)
        return local_path
    end

    # Artifact (auto-selects platform, triggers lazy download)
    try
        artifact_dir = @artifact_str("libnickel_lang")
        lib_path = joinpath(artifact_dir, LIB_NAME)
        if isfile(lib_path)
            return lib_path
        end
    catch
    end

    return nothing
end

# Library path and availability resolved at runtime via __init__(),
# not at precompile time. This allows Pkg.build() to install the library
# after initial precompilation (JLL pattern, requires Julia 1.6+).
libnickel_lang::String = ""
FFI_AVAILABLE::Bool = false

function __init_ffi__()
    path = _find_library_path()
    if path !== nothing
        global libnickel_lang = path
        global FFI_AVAILABLE = true
        Libdl.dlopen(path)
    end
end

include("libnickel.jl")
import .LibNickel
const L = LibNickel

"""
    check_ffi_available() -> Bool

Check if the Nickel C API library is available.
"""
check_ffi_available() = FFI_AVAILABLE

function _check_ffi_available()
    FFI_AVAILABLE && return
    error("Nickel C API library not available.\n\n" *
          "Install options:\n" *
          "  1. Build from source: NICKELEVAL_BUILD_FFI=true julia -e 'using Pkg; Pkg.build(\"NickelEval\")'\n" *
          "  2. Place $(LIB_NAME) in deps/ manually\n")
end

# ── Tree-walk: convert C API expr to Julia value ─────────────────────────────

function _walk_expr(expr::Ptr{L.nickel_expr})
    if L.nickel_expr_is_null(expr) != 0
        return nothing
    elseif L.nickel_expr_is_bool(expr) != 0
        return L.nickel_expr_as_bool(expr) != 0
    elseif L.nickel_expr_is_number(expr) != 0
        num = L.nickel_expr_as_number(expr)  # borrowed, no free
        if L.nickel_number_is_i64(num) != 0
            return L.nickel_number_as_i64(num)
        else
            return Float64(L.nickel_number_as_f64(num))
        end
    elseif L.nickel_expr_is_str(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_str(expr, out_ptr)
        return unsafe_string(out_ptr[], len)
    elseif L.nickel_expr_is_array(expr) != 0
        arr = L.nickel_expr_as_array(expr)  # borrowed, no free
        n = Int(L.nickel_array_len(arr))
        result = Vector{Any}(undef, n)
        if n > 0
            elem = L.nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    L.nickel_array_get(arr, UInt(i), elem)
                    result[i+1] = _walk_expr(elem)
                end
            finally
                L.nickel_expr_free(elem)
            end
        end
        return result
    elseif L.nickel_expr_is_record(expr) != 0
        rec = L.nickel_expr_as_record(expr)  # borrowed, no free
        n = Int(L.nickel_record_len(rec))
        result = Dict{String, Any}()
        if n > 0
            key_ptr = Ref{Ptr{Cchar}}(C_NULL)
            key_len = Ref{Csize_t}(0)
            val_expr = L.nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    L.nickel_record_key_value_by_index(rec, UInt(i), key_ptr, key_len, val_expr)
                    key = unsafe_string(key_ptr[], key_len[])
                    result[key] = _walk_expr(val_expr)
                end
            finally
                L.nickel_expr_free(val_expr)
            end
        end
        return result
    elseif L.nickel_expr_is_enum_variant(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        arg_expr = L.nickel_expr_alloc()
        try
            len = L.nickel_expr_as_enum_variant(expr, out_ptr, arg_expr)
            tag = Symbol(unsafe_string(out_ptr[], len))
            arg = _walk_expr(arg_expr)
            return NickelEnum(tag, arg)
        finally
            L.nickel_expr_free(arg_expr)
        end
    elseif L.nickel_expr_is_enum_tag(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = L.nickel_expr_as_enum_tag(expr, out_ptr)
        tag = Symbol(unsafe_string(out_ptr[], len))
        return NickelEnum(tag, nothing)
    else
        error("Unknown Nickel expression type")
    end
end

# ── Error extraction ──────────────────────────────────────────────────────────

function _throw_nickel_error(err::Ptr{L.nickel_error})
    out_str = L.nickel_string_alloc()
    try
        L.nickel_error_format_as_string(err, out_str, L.NICKEL_ERROR_FORMAT_TEXT)
        data_ptr = Ref{Ptr{Cchar}}(C_NULL)
        data_len = Ref{Csize_t}(0)
        L.nickel_string_data(out_str, data_ptr, data_len)
        msg = unsafe_string(data_ptr[], data_len[])
        throw(NickelError(msg))
    finally
        L.nickel_string_free(out_str)
    end
end

# ── Public API ────────────────────────────────────────────────────────────────

"""
    nickel_eval(code::String) -> Any

Evaluate Nickel code and return a Julia value.

Returns native Julia types: Int64, Float64, Bool, String, nothing,
Vector{Any}, Dict{String,Any}, or NickelEnum.

# Examples
```julia
julia> nickel_eval("1 + 2")
3

julia> nickel_eval("{ a = 1, b = 2 }")
Dict{String, Any}("a" => 1, "b" => 2)

julia> nickel_eval("let x = 5 in x * 2")
10
```
"""
function nickel_eval(code::String)
    _check_ffi_available()
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    try
        result = L.nickel_context_eval_deep(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _walk_expr(expr)
    finally
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

"""
    nickel_eval(code::String, ::Type{T}) -> T

Evaluate Nickel code and convert to type T.
Supports Dict, Vector, and NamedTuple conversions.

# Examples
```julia
julia> nickel_eval("42", Int)
42

julia> nickel_eval("{ a = 1, b = 2 }", Dict{String, Int})
Dict{String, Int64}("a" => 1, "b" => 2)

julia> nickel_eval("[1, 2, 3]", Vector{Int})
[1, 2, 3]

julia> nickel_eval("{ x = 1.5, y = 2.5 }", @NamedTuple{x::Float64, y::Float64})
(x = 1.5, y = 2.5)
```
"""
function nickel_eval(code::String, ::Type{T}) where T
    result = nickel_eval(code)
    return _convert_result(T, result)
end

# ── Type conversion helpers ───────────────────────────────────────────────────

_convert_result(::Type{T}, x) where T = convert(T, x)

function _convert_result(::Type{T}, d::Dict{String,Any}) where T <: NamedTuple
    fields = fieldnames(T)
    types = fieldtypes(T)
    values = Tuple(_convert_result(types[i], d[String(fields[i])]) for i in eachindex(fields))
    return T(values)
end

function _convert_result(::Type{Dict{K,V}}, d::Dict{String,Any}) where {K,V}
    return Dict{K,V}(K(k) => _convert_result(V, v) for (k, v) in d)
end

function _convert_result(::Type{Vector{T}}, v::Vector{Any}) where T
    return T[_convert_result(T, x) for x in v]
end

# ── File evaluation ───────────────────────────────────────────────────────────

"""
    nickel_eval_file(path::String) -> Any

Evaluate a Nickel file. Supports `import` statements resolved relative
to the file's directory.

Returns native Julia types: Int64, Float64, Bool, String, nothing,
Vector{Any}, Dict{String,Any}, or NickelEnum.

# Examples
```julia
julia> nickel_eval_file("config.ncl")
Dict{String, Any}("host" => "localhost", "port" => 8080)
```
"""
function nickel_eval_file(path::String)
    _check_ffi_available()
    abs_path = abspath(path)
    if !isfile(abs_path)
        throw(NickelError("File not found: $abs_path"))
    end
    code = read(abs_path, String)
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    try
        # Set source name to the absolute file path so Nickel can resolve imports
        # relative to the file's directory.
        GC.@preserve abs_path begin
            L.nickel_context_set_source_name(ctx, Base.unsafe_convert(Ptr{Cchar}, abs_path))
        end
        result = L.nickel_context_eval_deep(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _walk_expr(expr)
    finally
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

# ── Export (serialization) ────────────────────────────────────────────────────

function _eval_and_serialize(code::String, serialize_fn)
    _check_ffi_available()
    ctx = L.nickel_context_alloc()
    expr = L.nickel_expr_alloc()
    err = L.nickel_error_alloc()
    out_str = L.nickel_string_alloc()
    try
        result = L.nickel_context_eval_deep_for_export(ctx, code, expr, err)
        if result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        ser_result = serialize_fn(ctx, expr, out_str, err)
        if ser_result == L.NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        data_ptr = Ref{Ptr{Cchar}}(C_NULL)
        data_len = Ref{Csize_t}(0)
        L.nickel_string_data(out_str, data_ptr, data_len)
        return unsafe_string(data_ptr[], data_len[])
    finally
        L.nickel_string_free(out_str)
        L.nickel_error_free(err)
        L.nickel_expr_free(expr)
        L.nickel_context_free(ctx)
    end
end

"""
    nickel_to_json(code::String) -> String

Evaluate Nickel code and export to a JSON string.

# Examples
```julia
julia> nickel_to_json("{ a = 1, b = \"hello\" }")
"{\\"a\\": 1,\\"b\\": \\"hello\\"}"
```
"""
nickel_to_json(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_json)

"""
    nickel_to_yaml(code::String) -> String

Evaluate Nickel code and export to a YAML string.

# Examples
```julia
julia> nickel_to_yaml("{ a = 1 }")
"a: 1\\n"
```
"""
nickel_to_yaml(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_yaml)

"""
    nickel_to_toml(code::String) -> String

Evaluate Nickel code and export to a TOML string.

# Examples
```julia
julia> nickel_to_toml("{ a = 1 }")
"a = 1\\n"
```
"""
nickel_to_toml(code::String) = _eval_and_serialize(code, L.nickel_context_expr_to_toml)
