# FFI bindings to Nickel's official C API (v2.0.0)
# Low-level wrappers in libnickel.jl (generated by Clang.jl)
# This file provides the convenience layer: library discovery, eval, tree-walk.

using Artifacts: artifact_hash, artifact_path
using LazyArtifacts

# Platform-specific library name
const LIB_NAME = if Sys.isapple()
    "libnickel_lang.dylib"
elseif Sys.iswindows()
    "nickel_lang.dll"
else
    "libnickel_lang.so"
end

# Find library: local deps/ -> artifact -> not found
function _find_library_path()
    # Local deps/ (custom builds, HPC overrides)
    local_path = joinpath(@__DIR__, "..", "deps", LIB_NAME)
    if isfile(local_path)
        return local_path
    end

    # Artifact (auto-selects platform)
    # Use runtime API instead of @artifact_str to avoid compile-time errors
    # when artifact is not defined in Artifacts.toml for current platform.
    try
        artifacts_toml = joinpath(@__DIR__, "..", "Artifacts.toml")
        if isfile(artifacts_toml)
            hash = artifact_hash("libnickel_lang", artifacts_toml)
            if hash !== nothing
                artifact_dir = artifact_path(hash)
                lib_path = joinpath(artifact_dir, LIB_NAME)
                if isfile(lib_path)
                    return lib_path
                end
            end
        end
    catch
    end

    return nothing
end

const LIB_PATH = _find_library_path()
const FFI_AVAILABLE = LIB_PATH !== nothing

# Set the library path for LibNickel's @ccall wrappers.
# CRITICAL: this const must come before include("libnickel.jl") because the
# LibNickel module's @ccall uses `libnickel_lang` as a bare identifier
# imported from the parent module.
# Always define the const (even with empty string) so the import doesn't fail
# at compile time. The runtime check in _check_ffi_available() gates actual use.
const libnickel_lang = FFI_AVAILABLE ? LIB_PATH : ""

include("libnickel.jl")
using .LibNickel

"""
    check_ffi_available() -> Bool

Check if the Nickel C API library is available.
"""
check_ffi_available() = FFI_AVAILABLE

function _check_ffi_available()
    FFI_AVAILABLE && return
    error("Nickel C API library not available.\n\n" *
          "Install options:\n" *
          "  1. Build from source: NICKELEVAL_BUILD_FFI=true julia -e 'using Pkg; Pkg.build(\"NickelEval\")'\n" *
          "  2. Place $(LIB_NAME) in deps/ manually\n")
end

# ── Tree-walk: convert C API expr to Julia value ─────────────────────────────

function _walk_expr(expr::Ptr{LibNickel.nickel_expr})
    if nickel_expr_is_null(expr) != 0
        return nothing
    elseif nickel_expr_is_bool(expr) != 0
        return nickel_expr_as_bool(expr) != 0
    elseif nickel_expr_is_number(expr) != 0
        num = nickel_expr_as_number(expr)  # borrowed, no free
        if nickel_number_is_i64(num) != 0
            return nickel_number_as_i64(num)
        else
            return Float64(nickel_number_as_f64(num))
        end
    elseif nickel_expr_is_str(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = nickel_expr_as_str(expr, out_ptr)
        return unsafe_string(out_ptr[], len)
    elseif nickel_expr_is_array(expr) != 0
        arr = nickel_expr_as_array(expr)  # borrowed, no free
        n = Int(nickel_array_len(arr))
        result = Vector{Any}(undef, n)
        if n > 0
            elem = nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    nickel_array_get(arr, UInt(i), elem)
                    result[i+1] = _walk_expr(elem)
                end
            finally
                nickel_expr_free(elem)
            end
        end
        return result
    elseif nickel_expr_is_record(expr) != 0
        rec = nickel_expr_as_record(expr)  # borrowed, no free
        n = Int(nickel_record_len(rec))
        result = Dict{String, Any}()
        if n > 0
            key_ptr = Ref{Ptr{Cchar}}(C_NULL)
            key_len = Ref{Csize_t}(0)
            val_expr = nickel_expr_alloc()
            try
                for i in 0:(n-1)
                    nickel_record_key_value_by_index(rec, UInt(i), key_ptr, key_len, val_expr)
                    key = unsafe_string(key_ptr[], key_len[])
                    result[key] = _walk_expr(val_expr)
                end
            finally
                nickel_expr_free(val_expr)
            end
        end
        return result
    elseif nickel_expr_is_enum_variant(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        arg_expr = nickel_expr_alloc()
        try
            len = nickel_expr_as_enum_variant(expr, out_ptr, arg_expr)
            tag = Symbol(unsafe_string(out_ptr[], len))
            arg = _walk_expr(arg_expr)
            return NickelEnum(tag, arg)
        finally
            nickel_expr_free(arg_expr)
        end
    elseif nickel_expr_is_enum_tag(expr) != 0
        out_ptr = Ref{Ptr{Cchar}}(C_NULL)
        len = nickel_expr_as_enum_tag(expr, out_ptr)
        tag = Symbol(unsafe_string(out_ptr[], len))
        return NickelEnum(tag, nothing)
    else
        error("Unknown Nickel expression type")
    end
end

# ── Error extraction ──────────────────────────────────────────────────────────

function _throw_nickel_error(err::Ptr{LibNickel.nickel_error})
    out_str = nickel_string_alloc()
    try
        nickel_error_format_as_string(err, out_str, NICKEL_ERROR_FORMAT_TEXT)
        data_ptr = Ref{Ptr{Cchar}}(C_NULL)
        data_len = Ref{Csize_t}(0)
        nickel_string_data(out_str, data_ptr, data_len)
        msg = unsafe_string(data_ptr[], data_len[])
        throw(NickelError(msg))
    finally
        nickel_string_free(out_str)
    end
end

# ── Public API ────────────────────────────────────────────────────────────────

"""
    nickel_eval(code::String) -> Any

Evaluate Nickel code and return a Julia value.

Returns native Julia types: Int64, Float64, Bool, String, nothing,
Vector{Any}, Dict{String,Any}, or NickelEnum.

# Examples
```julia
julia> nickel_eval("1 + 2")
3

julia> nickel_eval("{ a = 1, b = 2 }")
Dict{String, Any}("a" => 1, "b" => 2)

julia> nickel_eval("let x = 5 in x * 2")
10
```
"""
function nickel_eval(code::String)
    _check_ffi_available()
    ctx = nickel_context_alloc()
    expr = nickel_expr_alloc()
    err = nickel_error_alloc()
    try
        result = nickel_context_eval_deep(ctx, code, expr, err)
        if result == NICKEL_RESULT_ERR
            _throw_nickel_error(err)
        end
        return _walk_expr(expr)
    finally
        nickel_error_free(err)
        nickel_expr_free(expr)
        nickel_context_free(ctx)
    end
end

"""
    nickel_eval(code::String, ::Type{T}) -> T

Evaluate Nickel code and convert to type T.
Supports Dict, Vector, and NamedTuple conversions.

# Examples
```julia
julia> nickel_eval("42", Int)
42

julia> nickel_eval("{ a = 1, b = 2 }", Dict{String, Int})
Dict{String, Int64}("a" => 1, "b" => 2)

julia> nickel_eval("[1, 2, 3]", Vector{Int})
[1, 2, 3]

julia> nickel_eval("{ x = 1.5, y = 2.5 }", @NamedTuple{x::Float64, y::Float64})
(x = 1.5, y = 2.5)
```
"""
function nickel_eval(code::String, ::Type{T}) where T
    result = nickel_eval(code)
    return _convert_result(T, result)
end

# ── Type conversion helpers ───────────────────────────────────────────────────

_convert_result(::Type{T}, x) where T = convert(T, x)

function _convert_result(::Type{T}, d::Dict{String,Any}) where T <: NamedTuple
    fields = fieldnames(T)
    types = fieldtypes(T)
    values = Tuple(_convert_result(types[i], d[String(fields[i])]) for i in eachindex(fields))
    return T(values)
end

function _convert_result(::Type{Dict{K,V}}, d::Dict{String,Any}) where {K,V}
    return Dict{K,V}(K(k) => _convert_result(V, v) for (k, v) in d)
end

function _convert_result(::Type{Vector{T}}, v::Vector{Any}) where T
    return T[_convert_result(T, x) for x in v]
end
